version: "3.2"

services:

  arangodb:
    image: arangodb/arangodb:3.6.0
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - ./compose/arangodb:/var/lib/arangodb3
    ports:
      - 8529:8529
    command: "arangod --server.endpoint tcp://0.0.0.0:8529"
